apiVersion: apps/v1
kind: Deployment
metadata:
  name: stresstest-depl
spec:
  selector:
    matchLabels:
      app: stresstest
  template:
    metadata:
      labels:
        app: stresstest
    spec:
      containers:
      - name: stresstest
        image: alegotta/stress-test
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: stresstest-svc
  labels:
    app: stresstest
spec:
  type: LoadBalancer
  selector:
    app: stresstest
  ports:
  - port: 80
