apiVersion: apps/v1
kind: Deployment
metadata:
  name: stresstest-depl
spec:
  selector:
    matchLabels:
      app: stresstest
  template:
    metadata:
      labels:
        app: stresstest
    spec:
      containers:
      - name: stresstest
        image: alegotta/stress-test:1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: stresstest-svc
  labels:
    app: stresstest
spec:
  type: LoadBalancer
  selector:
    app: stresstest
  ports:
  - port: 80

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: stresstest-scaler
  labels:
    app: stresstest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stresstest-depl
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
